<?php

function server_management_twoway_service() {
  return array(
    'server_connect' => array(
      'callback' => 'server_management_service_do_server_connect',
      'service_file' => 'services/server_management.server_connect.inc',
      'description' => 'Requests that services be sent between the servers',
    ),
  );
}

function server_management_secsyn_entity_dependency($entity) {
  $deps = array();
  switch ($entity->entity_type) {
    case 'server':
      if (!empty($entity->parent_sid)) {
        $server = server_management_load($entity->parent_sid);
        $deps[] = array(
          'object' => $server,
          'profile' => 'SecureSyndicationEntityProfile',
        );
      }
      break;
    case 'server_config':
      $server = server_management_load($entity->sid);
      $deps[] = array(
        'object' => $server,
        'profile' => 'SecureSyndicationEntityProfile',
      );
      break;
  }
  return $deps;
}

function server_management_yamlconfig_handlers() {
  return array(
    'server_config_type' => array(
      'weight' => 500,
    ),
  );
}

function server_management_config_type_delete($type) {
  db_delete('server_management_config_types')
      ->condition('type', $type)
      ->execute();
  field_attach_delete_bundle('server_config', $type);
}

function server_management_secsyn_entity_children($entity) {
  $deps = array();
  switch ($entity->entity_type) {
    case 'server':
      $packets = server_management_config_item_load($entity->sid);
      foreach ($packets as $packet) {
        $packet->entity_type = 'server_config';
        $deps[] = array(
          'object' => $packet,
          'profile' => 'SecureSyndicationEntityProfile',
        );
      }
      break;
  }
  return $deps;
}

function server_management_secsyn_entity_ignore_fields($entity) {
switch ($entity->entity_type) {
    case 'server':
      return array('sid', 'parent_sid');
      break;
    case 'server_config':
      return array('cid', 'sid');
      break;
  }
}

function server_management_secsyn_entity_package_alter(&$package, $object) {
  switch ($object->entity_type) {
    case 'server':
      if (!empty($object->parent_sid)) {
        $parent = server_management_load($object->parent_sid);
        $package->parent_server = $parent->machine_name;
      }
      break;
    case 'server_config':
      $parent = server_management_load($object->sid);
      $package->parent_server = $parent->machine_name;
      break;
  }
}

function server_management_secsyn_entity_presave(&$entity) {
  switch ($entity->entity_type) {
    case 'server':
      if (!empty($entity->parent_server)) {
        $server = server_management_load_by_name($entity->parent_server);
        $entity->parent_sid = $server->sid;
        unset($entity->parent_server);
      }
      break;
    case 'server_config':
      $server = server_management_load_by_name($entity->parent_server);
      $entity->sid = $server->sid;
      unset($entity->parent_server);
      break;
  }
}

function server_management_server_load_by_parent($parent_sid = NULL) {
  $efq = new EntityFieldquery();
  $efq->entityCondition('entity_type', 'server');
  if (empty($parent_sid)) {
    $efq->propertyCondition('parent_sid', 1, '<');
  } else {
    $efq->propertycondition('parent_sid', $parent_sid);
  }
  $results = array();
  $rs = $efq->execute();
  if (empty($rs['server'])) {
    return array();
  }
  foreach (array_keys($rs['server']) as $sid) {
    $results[$sid] = server_management_load($sid);
  }
  return $results;
}

function server_management_delete_server($server) {
  $controller = entity_get_controller('server');
  $controller->delete(array($server->sid));
}

function server_management_delete_config($config) {
  $controller = entity_get_controller('server_config');
  $controller->delete(array($config->cid));
}

function server_management_config_item_load($server_id) {
  $q = db_select('server_management_config', 'smc');
  $q->fields('smc');
  $q->condition('sid', $server_id);
  return $q->execute()->fetchAll();
}

function server_management_config_types() {
  if (!db_table_exists('server_management_config_types')) {
    return array();
  }
  $types = array();
  $results = db_query('SELECT * FROM {server_management_config_types} ORDER BY `label`');
  foreach ($results as $result) {
    $types[$result->type] = $result;
  }
  return $types;
}

function server_management_config_type_name_exists($name) {
  $existing = array_keys(server_management_config_types());
  return in_array($name, $existing);
}

function server_management_entity_info() {
  $bundles = array();
  foreach (server_management_config_types() as $type) {
    $bundles[$type->type] = array(
      'label' => $type->label,
      'admin' => array(
        'path' => 'admin/structure/server_config/manage/%server_management_config_type',
        'real path' => 'admin/structure/server_config/manage/' . $type->type,
        'bundle argument' => 4,
        'access arguments' => array('administer server fields'),
      ),
    );
  }
  return array(
    'server_config' => array(
      'label' => t('Server Configuration'),
      'entity class' => 'Entity',
      'controller class' => 'ServerConfigurationEntityController',
      'base table' => 'server_management_config',
      'load hook' => 'server_management_config_load',
      'access callback' => 'server_management_config_access',
      'bundle_load' => 'server_management_config_type_api_load',
      'bundle_save' => 'server_management_config_type_api_save',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'cid',
        'label' => 'label',
        'bundle' => 'type',
        'custom uuid' => 'uuid',
      ),
      'bundles' => $bundles,
    ),
    'server' => array(
      'label' => t('Server'),
      'entity class' => 'Entity',
      'controller class' => 'ServerEntityController',
      'base table' => 'server_management_servers',
      'load hook' => 'server_management_load',
      'access callback' => 'server_management_access',
      'bundle load' => 'server_management_type_api_load',
      'bundle save' => 'server_management_type_api_save',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'sid',
        'label' => 'label',
        'custom uuid' => 'machine_name',
      ),
      'bundles' => array(
        'server' => array(
          'label' => 'Server',
          'admin' => array(
            'path' => 'admin/structure/servers/manage/server',
            'access arguments' => array('administer server fields'),
          ),
        ),
      ),
    ),
  );
}

function server_management_type_api_load() {
  return (object) array('server' => TRUE);
}

function server_management_type_api_save() {
  return TRUE;
}

function server_management_config_type_api_load($entity_type, $bundle_name) {
  $types = server_management_config_types();
  if (empty($types[$bundle_name])) {
    return FALSE;
  }
  return $types[$bundle_name];
}

function server_management_config_type_api_save($bundle_def) {
  unset($bundle_def['entity_type']);
  unset($bundle_def['bundle_name']);
  return server_management_config_type_save($bundle_def);
}

function server_management_config_type_save($type) {
  return db_merge('server_management_config_types')
      ->fields((array) $type)
      ->key(array('type' => $type['type']))
      ->execute();
}

function server_management_theme() {
  return array(
    'server' => array(
      'variables' => array(
        'server' => NULL,
        'view_mode' => 'full',
      ),
      'template' => 'server',
    ),
  );
}

function server_management_config_type_load($type) {
  $types = server_management_config_types();
  if (isset($types[$type])) {
    return $type;
  }
  return FALSE;
}

function server_management_menu() {
  $admin_common = array(
    'file' => 'server_management.admin.inc',
    'access arguments' => array('administer server fields'),
  );
  $menu = array();
  $menu['admin/structure/servers'] = array(
    'title' => 'Managed Servers',
    'description' => 'Manage settings for managed servers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('server_management_server_form'),
  ) + $admin_common;
  $menu['admin/structure/server_config'] = array(
    'title' => 'Server Configuation Packets',
    'description' => 'Manage the different types of information that we can store about servers',
    'page callback' => 'server_management_config_list_types',
    'type' => MENU_NORMAL_ITEM,
  ) + $admin_common;
  $menu['admin/structure/server_config/list'] = array(
    'title' => 'List',
    'weight' => -20,
    'type' =>  MENU_DEFAULT_LOCAL_TASK & MENU_LOCAL_TASK,
  ) + $admin_common;
  $menu['admin/structure/server_config/add'] = array(
    'title' => 'Add Configuration Bundle',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('server_management_config_type_form'),
  ) + $admin_common;
  $menu['admin/structure/server_config/manage/%server_management_config_type'] = array(
    'title' => 'Edit Configuration Type',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('server_management_config_type_form', 4),
  ) + $admin_common;
  $menu['admin/structure/server_config/manage/%server_management_config_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK & MENU_LOCAL_TASK,
    'weight' => -20,
  ) + $admin_common;
  return $menu;
}

function server_management_config_load($cid) {
  $controller = entity_get_controller('server_config');
  return reset($controller->load(array($cid)));
}

function server_management_name_exists($machine_name) {
  $server = server_management_load_by_name($machine_name);
  return !empty($server);
}

function server_management_save_server(&$server) {
  $controller = entity_get_controller('server');
  $controller->save($server);
}

function server_management_load($server_id) {
  $controller = entity_get_controller('server');
  return reset($controller->load(array($server_id)));
}

function server_management_load_by_name($server_name) {
  $efq = new EntityFieldQuery();
  $efq->entityCondition('entity_type', 'server');
  $efq->propertyCondition('machine_name', $server_name);
  $results = $efq->execute();
  if (empty($results)) {
    return FALSE;
  }
  return server_management_load(reset(array_keys($results['server'])));
}

function server_management_permission() {
  return array(
    'administer servers' => array(
      'title' => t('Server Access'),
      'description' => t('Allows user to administer server information'),
    ),
    'administer server fields' => array(
      'title' => t('Field Access'),
      'description' => t('Allows user to administer server fields'),
    ),
  );
}

function server_management_access() {
  return user_access('administer servers');
}

function server_management_config_access() {
  return user_access('administer servers');
}
